### ISSUE TITLE
Clear/dismiss notification on click

### ISSUE THREAD

**Issue by suprajas** [DavidBriglio/cordova-plugin-local-notifications#2]
Hi,
Thanks for this fork. I was raking my head to get the action buttons working. 
I have two actions: Yes and No. On clicking 'Yes' action, the user is navigated to a specific page in the app. This part works perfectly. But when the user click 'No' I would merely like to clear the notification without bringing the app into the foreground. 
What could be going wrong? 
Here are the actions i have-
actions: [{
                val: 2,
                text: 'No'
            },
            {
                val: 1,
                text: 'Yes'
            }],

And here is the click handler-
cordova.plugins.notification.local.on("click", function (notification) {
            if (notification.actionClicked.val==1){
                window.location.href = "myPage.html";
            }
            if (notification.actionClicked.val==2) {
                cordova.plugins.notification.local.clear(1, function () {
                    //alert("done");
                });
            }
            
        });

**Comment by DavidBriglio** [comment]
I'm sorry for the late response, and I'm sure you have probably found a solution. In the current implementation it will always bring the application to the foreground. If the user does not want to click "Yes" they should clear the notification instead of having an option for "No". With the current implementation I would suggest modifying the wording of your notification as to not require a binary response.

**Comment by suprajas** [comment]
Yeah thanks. That is exactly what I did. I had to send it out in a rush and did not really find time to work out a solution yet. If I do find a way out, I shall post back :)
